### ISSUE TITLE
Roadmap / todos

### ISSUE THREAD

**Issue by vadimnazarov** [imminfo/ymir-rpackage#1]
Features
--

#### Basic interface to Ymir
- [ ] Compute generation probabilities.
- [ ] Statistical inference.
- [ ] Artificial repertoire generation.

#### Analysis
- [ ] Out-of-frame sharing estimation.
- [ ] Mixed models.
- [ ] Model-repertoire heatmap.
- [ ] Various plots.
